### PR TITLE
new feature - network disconnect

### PR DESCRIPTION
**Pull request by navidys**
Adding network disconnect command to network page view. 

podman_network_disconnect

Signed-off-by: Navid Yaghoobi <navidys@fedoraproject.org>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@navidys BTW, any interest in working on podman-desktop?

**Comment by navidys** [comment]
Hi @rhatdan 
I am intrested to work on podman-desktop as well however need to improve my type script programming.

**Comment by rhatdan** [comment]
Awesome.  I am sure they would love the help.
@benoitf FYI

**Comment by benoitf** [comment]
yes, you're welcome 👍

**Comment by navidys** [comment]
@benoitf thanks a lot and more than happy to help , at the moment I am making my self familair with the podman-dekstop code and its capabiltities.

**Comment by benoitf** [comment]
@navidys if you have questions, we can do a chat or discuss it this upcoming week

**Pull request merged**
