### PR TITLE
adding format and security options fields to image build dialog

### PR DESCRIPTION
**Pull request by navidys**
1. Adding "**Output format**" dropdown primitive with "oci" and "docker" items to select
2. Adding "**Security Options**" category page with following input fields:
    -  SELinux contexts
    -  Apparmor profile
    - Seccomp profile
image_build

Signed-off-by: Navid Yaghoobi <n.yaghoobi.s@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
I would refer to SELinux label or just label (This is what the CLI does)
Add a check box for no-new-privileges, 
You should also handle mask and unmask.

**Comment by navidys** [comment]
Hi @rhatdan 

- I have updated the inputfields label. 
image-build-security-options
- For "mask/umask and no-new-privileges" security options, correct me if I am wrong , I think I need to add these options to "container create/run" dialogs since image build doesn't have these options. 

At the moment "container create" dialog is totally missing "security options" fields which I am going to add in different PR if its ok with you.

**Comment by rhatdan** [comment]
Yes I believe you are create, these flags are not supported currently for build, which might be an oversight on our part.

**Comment by navidys** [comment]
> Yes I believe you are create, these flags are not supported currently for build, which might be an oversight on our part.

I added the security options to pod create and container create dialogs. @rhatdan do you think its ok now to merge this PR as well.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
