### PR TITLE
readme: add AUR mention

### PR DESCRIPTION
**Pull request by misobarisic**
I have published 2 AUR packages regarding this project and wanted to mention them in the readme just in case.

### CODE REVIEW

**Comment by navidys** [comment]
Hi @misobarisic 
Thanks for that, it looks like there are some concern about the [package](https://aur.archlinux.org/packages/podman-tui).

**Comment by misobarisic** [comment]
> Hi @misobarisic 
> Thanks for that, it looks like there are some concern about the [package](https://aur.archlinux.org/packages/podman-tui).
> 

The `issues` should be fixed relatively soon.

**Comment by navidys** [comment]
Hi @rhatdan
Do you think we should put reference to AUR repository under README or under separate file (install.md) ? 
Also my undrestanding this is user repository type and not offical Arch repo.

**Comment by rhatdan** [comment]
It should go into install.md

**Comment by misobarisic** [comment]
PKGBUILDs have been updated to better reflect needed dependencies (for systems without `base-devel`). I've tested it on a clean Arch system without an AUR helper. Works as expected.

**Comment by misobarisic** [comment]
Created `INSTALL.md` and I believe this PR is ready to be merged.

**Comment by navidys** [comment]
LGTM

**Pull request merged**
